trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'takkie-animation-env-python-docker'
  dockerfilePath: 'Dockerfile'

steps:
- task: Docker@2
  displayName: Build Docker image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: $(dockerfilePath)
    tags: |
      latest
      $(Build.BuildId)